# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: limelight
email: limelight-help@yeastrc.org
author: Michael Riffle
description: > # "Write an awesome description for your new site here. 
  Limelight is a platform for analyzing, visualizing, and sharing mass spectrometry proteomics data.
copyright: 'Copyright &copy; 2022 Michael Riffle. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: question-circle
    text: Documentation
    url: https://limelight-ms.readthedocs.org/
  - icon: github
    text: View Source Code
    url: https://github.com/yeastrc/limelight-core
