version: "3.9"

volumes:
  mysqldb:
  spectr_upload:
  spectr_storage:
  limelight_upload:
  limelight_blib_downloads:
  blib_export_workdir:
  feature_detection_workdir:
  feature_detection_finaldir:

services:
  db:
    image: mysql:8.0
    container_name: limelight-mysql
    restart: always
    command: ${MYSQL_OPTIONS}
    volumes:
      - mysqldb:/var/lib/mysql
      - ./database_scripts/install:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: limelight
  spectr:
    image: mriffle/spectr:1
    container_name: limelight-spectr
    restart: always
    environment:
      SPECTRAL_STORAGE_MAX_SCAN_BATCH_SIZE : ${SPECTR_MAX_SCAN_BATCH_SIZE:-200}
    volumes:
      - spectr_upload:/data/upload
      - spectr_storage:/data/storage
      - limelight_upload:/data/limelight_upload
  blib-export:
    image: mriffle/limelight-export-blib-service:1
    container_name: limelight-export-blib-service
    restart: always
    labels:
      - traefik.enable=false
    environment:
      SPECTR_GET_SCAN_DATA_URL: http://spectr:8080/spectral_storage_get_data/query/getScanDataFromScanNumbers_JSON
      WEBAPP_PORT: 3434
      APP_CLEAN_WORKDIR: ${BLIB_APP_CLEAN_WORKDIR:-yes}
      SPECTR_BATCH_SIZE: ${SPECTR_MAX_SCAN_BATCH_SIZE:-200}
    volumes:
      - limelight_blib_downloads:/data/app/blibdir
      - blib_export_workdir:/data/app/workdir
  feature-detection:
    image: mriffle/limelight-feature-detection-service:1
    container_name: limelight-feature-detection-service
    restart: always
    labels:
      - traefik.enable=false
    environment:
      SPECTR_GET_SCAN_DATA_URL: http://spectr:8080/spectral_storage_get_data/query/getScanDataFromScanNumbers_JSON
      SPECTR_GET_SCAN_NUMBERS_URL: http://spectr:8080/spectral_storage_get_data/query/getScanNumbers_JSON
      SPECTR_BATCH_SIZE: ${SPECTR_MAX_SCAN_BATCH_SIZE:-200}
      WEBAPP_PORT: 3434
      APP_CLEAN_WORKDIR: ${FEATURE_DETECTION_CLEAN_WORKDIR:-yes}
    volumes:
      - feature_detection_finaldir:/data/app/finaldir
      - feature_detection_workdir:/data/app/workdir
  importer:
    image: mriffle/limelight-importer:4.0.0-rc.1
    container_name: limelight-importer
    restart: always
    depends_on:
      - db
    volumes:
      - limelight_upload:/data/limelight_upload
    environment:
      LIMELIGHT_DB_USER: ${MYSQL_USER}
      LIMELIGHT_DB_PASSWORD: ${MYSQL_PASSWORD}
      LIMELIGHT_DB_HOST_ADDRESS: db
      LIMELIGHT_DB_HOST_PORT: 3306
      LIMELIGHT_DB_NAME: limelight
      LIMELIGHT_JAVA_EXECUTE_PARAMS: ${IMPORTER_JAVA_OPTIONS}
  limelight:
    image: mriffle/limelight-webapp:4.0.0-rc.1
    container_name: limelight-webapp
    restart: always
    depends_on:
      - db
    volumes:
      - limelight_upload:/data/limelight_upload
      - limelight_blib_downloads:/data/limelight_downloads/blib_exports
      - feature_detection_finaldir:/data/feature_detection/finaldir
    environment:
      LIMELIGHT_MYSQL_USER: ${MYSQL_USER}
      LIMELIGHT_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 8080:8080
  smtp:
    image: bytemark/smtp
    container_name: limelight-smtp
    restart: always
    environment:
      RELAY_HOST: ${SMTP_HOST}
      RELAY_PORT: ${SMTP_PORT}
      RELAY_USERNAME: ${SMTP_USERNAME}
      RELAY_PASSWORD: ${SMTP_PASSWORD}
