package org.yeastrc.limelight.limelight_webapp.searchers;

import org.yeastrc.limelight.limelight_webapp.searchers.FeatureDetection_SingularFeature_Entries_For_FeatureDetectionRootId_Searcher.FeatureDetection_SingleFeature_Entries_For_FeatureDetectionRootId_Searcher_Result;

public interface FeatureDetection_SingularFeature_Entries_For_FeatureDetectionRootId_Searcher_IF {

	FeatureDetection_SingleFeature_Entries_For_FeatureDetectionRootId_Searcher_Result getForFeatureDetectionRootId(
			int searchId) throws Exception;

}