package org.yeastrc.limelight.limelight_webapp.searchers;

import org.yeastrc.limelight.limelight_webapp.searchers.FeatureDetection_Root_Mapping_Entries_For_ProjectId_Searcher.FeatureDetection_Root_Mapping_Entries_For_ProjectId_Searcher_Result;

public interface FeatureDetection_Root_Mapping_Entries_For_ProjectId_Searcher_IF {

	FeatureDetection_Root_Mapping_Entries_For_ProjectId_Searcher_Result getForProjectId(int projectId) throws Exception;

}