package org.yeastrc.limelight.limelight_webapp.searchers;

import org.yeastrc.limelight.limelight_webapp.searchers.Feature_detection_root_Id_For_Feature_detection_root__project_scnfl_mapping_tbl_id__ProjectSearchId_Searcher.Feature_detection_root_Id_For_Feature_detection_root__project_scnfl_mapping_tbl_id__ProjectSearchId_Searcher_Result;

public interface Feature_detection_root_Id_For_Feature_detection_root__project_scnfl_mapping_tbl_id__ProjectSearchId_Searcher_IF {

	Feature_detection_root_Id_For_Feature_detection_root__project_scnfl_mapping_tbl_id__ProjectSearchId_Searcher_Result feature_detection_root__project_scnfl_mapping_tbl__id_ValidateIsIn_ProjectSearchId__For_projectSearchId_feature_detection_root__project_scnfl_mapping_tbl__id(

			int projectSearchId, int feature_detection_root__project_scnfl_mapping_tbl__id) throws Exception;

}