package org.yeastrc.limelight.limelight_webapp.searchers;

import org.yeastrc.limelight.limelight_webapp.searchers.FeatureDetection_ProjectIdFor_FeatureDetectionRoot_MappingTblId_Searcher.FeatureDetection_ProjectIdFor_FeatureDetectionRoot_MappingTblId_Searcher_Result;

public interface FeatureDetection_ProjectIdFor_FeatureDetectionRoot_MappingTblId_Searcher_IF {

	FeatureDetection_ProjectIdFor_FeatureDetectionRoot_MappingTblId_Searcher_Result getProjectIdFor_FeatureDetectionRoot_MappingTblId(
			int persistentToSingular_Feature_Entry_Id) throws Exception;

}