package org.yeastrc.limelight.limelight_webapp.searchers;

import java.util.List;

import org.yeastrc.limelight.limelight_webapp.searchers.FeatureDetection_SingularFeature_Entries_For_FeatureDetectionRootId_Searcher.FeatureDetection_SingleFeature_Entries_For_FeatureDetectionRootId_Searcher_Result;

public interface FeatureDetection_SingularFeature_Entries_For_FeatureDetectionRootId_Searcher_IF {

	FeatureDetection_SingleFeature_Entries_For_FeatureDetectionRootId_Searcher_Result getForFeatureDetectionRootId_StartId_EndId(
			int featureDetectionRootId, int startId, int endId) throws Exception;

	FeatureDetection_SingleFeature_Entries_For_FeatureDetectionRootId_Searcher_Result  getForFeatureDetectionRootId_SingularFeatureIds_List(

			int featureDetectionRootId, List<Integer> singularFeatureIds_List 

			) throws Exception;
}