package org.yeastrc.limelight.limelight_webapp.searchers;

import org.yeastrc.limelight.limelight_webapp.searchers.FeatureDetection_PersistentFeature_Entries_For_FeatureDetectionRootId_Searcher.FeatureDetection_PersistentFeature_Entries_For_FeatureDetectionRootId_Searcher_Result;

public interface FeatureDetection_PersistentFeature_Entries_For_FeatureDetectionRootId_Searcher_IF {

	FeatureDetection_PersistentFeature_Entries_For_FeatureDetectionRootId_Searcher_Result getForFeatureDetectionRootId(
			int featureDetectionRootId) throws Exception;

}