package org.yeastrc.limelight.limelight_webapp.searchers;

import java.util.List;

import org.yeastrc.limelight.limelight_webapp.searchers.ProteinCoverage_ProteinSequenceVersionId_ProteinStartPosition_For_SearchIdReportedPeptideId_Searcher.ProteinCoverage_ProteinSequenceVersionId_ProteinStartPosition_For_SearchIdReportedPeptideId_Searcher_ResultItem;

public interface ProteinCoverage_ProteinSequenceVersionId_ProteinStartPosition_For_SearchIdReportedPeptideId_Searcher_IF {

	List<ProteinCoverage_ProteinSequenceVersionId_ProteinStartPosition_For_SearchIdReportedPeptideId_Searcher_ResultItem>

			getProteinCoverage_ProteinSequenceVersionId_ProteinStartPosition_For_SearchIdReportedPeptideId(int searchId,
					int reportedPeptideId) throws Exception;

}