package org.yeastrc.limelight.limelight_webapp.searchers;

import java.util.List;

import org.yeastrc.limelight.limelight_shared.searcher_psm_peptide_cutoff_objects.SearcherCutoffValuesSearchLevel;
import org.yeastrc.limelight.limelight_webapp.searchers.PsmReporterIonMassesForSearchIdReportedPeptideIdCutoffsSearcher.PsmReporterIonMassesForSearchIdReportedPeptideIdCutoffsSearcher_ResultEntry;

public interface PsmReporterIonMassesForSearchIdReportedPeptideIdCutoffsSearcherIF {

	List<PsmReporterIonMassesForSearchIdReportedPeptideIdCutoffsSearcher_ResultEntry> getPsmReporterIonMassesForSearchIdReportedPeptideIdCutoffs(

			int reportedPeptideId, int searchId, SearcherCutoffValuesSearchLevel searcherCutoffValuesSearchLevel)
			throws Exception;

}