/**
 * centralPageStateManager_Keys.ts
 * 
 * Keys that components will use in their functions getUniqueId()
 * 
 * Normally make a key a single character or 2 characters to save space on URL
 */

//////////////////////////////////
// JavaScript directive:   all variables have to be declared with "var", maybe other things
"use strict";

const SINGLE_PROTEIN__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY = 'a';
const CENTRAL_STATE_MANAGER_OBJECT_CLASS__SEARCH_COLOR_STATE_MANAGER_KEY = 'b';
const PROTEIN_LIST__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY = 'c';
const MOD_VIEW_MULTI_SEARCH_DATA_VIZ__CENTRAL_STATE_MANAGER_KEY = 'd';
const SINGLE_PROTEIN_EXPERIMENT_PAGE__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY = 'e';
const PROTEIN_GROUPING__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY = 'f';
const PROTEIN_EXPERIMENT_PAGE_SELECTED_CONDITION_IDS_CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY = 'g';
const SEARCH_SUB_GROUP_SELECTION_CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY = 'h';
const PEPTIDE_LIST__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY = 'i';
const PEPTIDE_EXPERIMENT_LIST__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY = 'j';
const PROTEIN_LIST_EXPERIMENT_PAGE__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY = 'k';

export {
    SINGLE_PROTEIN__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY,
    CENTRAL_STATE_MANAGER_OBJECT_CLASS__SEARCH_COLOR_STATE_MANAGER_KEY,
    PROTEIN_LIST__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY,
    MOD_VIEW_MULTI_SEARCH_DATA_VIZ__CENTRAL_STATE_MANAGER_KEY,
    SINGLE_PROTEIN_EXPERIMENT_PAGE__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY,
    PROTEIN_GROUPING__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY,
    PROTEIN_EXPERIMENT_PAGE_SELECTED_CONDITION_IDS_CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY,
    SEARCH_SUB_GROUP_SELECTION_CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY,
    PEPTIDE_LIST__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY,
    PEPTIDE_EXPERIMENT_LIST__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY,
    PROTEIN_LIST_EXPERIMENT_PAGE__CENTRAL_STATE_MANAGER_OBJECT_CLASS__CENTRAL_STATE_MANAGER_KEY
}
