package org.yeastrc.limelight.limelight_webapp.send_email_extra_on_import_finish;

import org.yeastrc.limelight.limelight_webapp.send_email_extra_on_import_finish.SendEmail_Extra_On_ImporterFinish_ToConfiguredEmail_ReadConfig.SendEmail_Extra_On_ImporterFinish_ToConfiguredEmail_ReadConfig_Response;

public interface SendEmail_Extra_On_ImporterFinish_ToConfiguredEmail_ReadConfig_IF {

	/**
	 * @return
	 */

	SendEmail_Extra_On_ImporterFinish_ToConfiguredEmail_ReadConfig_Response sendEmail_Extra_On_ImporterFinish_ToConfiguredEmail_ReadConfig()
			throws Exception;

}