package org.yeastrc.limelight.limelight_webapp.blib_file__creation_web_service__call_webservice_code;

import org.yeastrc.limelight.limelight_webapp.blib_file__creation_web_service__call_webservice_code.BlibSpectralLibrary_File_Creation_WebService__GetCreationStatus__CallWebService.BlibSpectralLibrary_File_Creation_WebService__GetCreationStatus__CallWebService_Response;
import org.yeastrc.limelight.limelight_webapp.blib_file__creation_web_service__call_webservice_code.BlibSpectralLibrary_File_Creation_WebService__GetCreationStatus__CallWebService.Request_To_BlibCreator_Status_Webservice_Root;

public interface BlibSpectralLibrary_File_Creation_WebService__GetCreationStatus__CallWebService_IF {

	BlibSpectralLibrary_File_Creation_WebService__GetCreationStatus__CallWebService_Response blibFileCreation_WebService__GetCreationStatus__CallWebService(
			Request_To_BlibCreator_Status_Webservice_Root request_To_BlibCreator_Webservice_Root) throws Exception;

}